# coding=utf-8

API_METHOD = {
    # location
    '/v2/location/feed/list': 'get',
    '/v2/location/get': 'get',
    # album
    '/v2/album/list': 'get',
    '/v2/album/get': 'get',
    '/v2/album/put': 'post',
    # blog
    '/v2/blog/list': 'get',
    '/v2/blog/put': 'post',
    '/v2/blog/get': 'get',
    # vipinfo
    '/v2/vipinfo/get': 'get',
    # evaluation
    '/v2/evaluation/reply/put': 'post',
    '/v2/evaluation/reply/list': 'get',
    '/v2/evaluation/put': 'post',
    # share
    '/v2/share/ugc/put': 'post',
    '/v2/share/hot/list': 'get',
    '/v2/share/url/put': 'post',
    '/v2/share/get': 'get',
    '/v2/share/list': 'get',
    # ubb
    '/v2/ubb/list': 'get',
    # notification
    '/v2/notification/user/put': 'post',
    '/v2/notification/app/put': 'post',
    # feed
    '/v2/feed/put': 'post',
    '/v2/feed/list': 'get',
    # place
    '/v2/place/friend/feed/list': 'get',
    '/v2/place/put': 'post',
    '/v2/place/feed/list': 'get',
    '/v2/place/list': 'get',
    # profile
    '/v2/profile/get': 'get',
    # app
    '/v2/app/get': 'get',
    # status
    '/v2/status/get': 'get',
    '/v2/status/put': 'post',
    '/v2/status/list': 'get',
    '/v2/status/share': 'post',
    # like
    '/v2/like/ugc/remove': 'post',
    '/v2/like/ugc/put': 'post',
    '/v2/like/ugc/info/get': 'get',
    # photo
    '/v2/photo/upload': 'post',
    '/v2/photo/get': 'get',
    '/v2/photo/list': 'get',
    # checkin
    '/v2/checkin/reply/list': 'get',
    '/v2/checkin/put': 'post',
    '/v2/checkin/get': 'get',
    '/v2/checkin/list': 'get',
    '/v2/checkin/reply/put': 'post',
    # comment
    '/v2/comment/put': 'post',
    '/v2/comment/list': 'get',
    # user
    '/v2/user/batch': 'get',
    '/v2/user/get': 'get',
    '/v2/user/friend/list': 'get',
    '/v2/user/friend/uninstall/list': 'get',
    '/v2/user/friend/mutual/list': 'get',
    '/v2/user/friend/app/list': 'get',
    '/v2/user/login/get': 'get',
    # friend
    '/v2/friend/list': 'get',
}
